// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-svc-tpl/internal/dao/ent/link"
	"go-svc-tpl/internal/dao/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	linkFields := schema.Link{}.Fields()
	_ = linkFields
	// linkDescShort is the schema descriptor for short field.
	linkDescShort := linkFields[1].Descriptor()
	// link.ShortValidator is a validator for the "short" field. It is called by the builders before save.
	link.ShortValidator = linkDescShort.Validators[0].(func(string) error)
	// linkDescComment is the schema descriptor for comment field.
	linkDescComment := linkFields[3].Descriptor()
	// link.DefaultComment holds the default value on creation for the comment field.
	link.DefaultComment = linkDescComment.Default.(string)
	// linkDescActive is the schema descriptor for active field.
	linkDescActive := linkFields[6].Descriptor()
	// link.DefaultActive holds the default value on creation for the active field.
	link.DefaultActive = linkDescActive.Default.(bool)
}
